### ISSUE TITLE
Remove Copyright from CC License in Footer

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-gatsby-theme#1]
![image](https://github.com/Riverscapes/riverscapes-gatsby/assets/9723905/1df65f34-2d1a-43e2-b223-ce51b14263be)
- [x] Link "Riverscapes Consortium" to http://creativecommons.org/licenses/by/4.0/
- [x] Remove "Copyright"
- [ ] Later, all our sites will do something like this in the footer:
![image](https://github.com/Riverscapes/riverscapes-gatsby/assets/9723905/24435ef3-a638-41eb-ba42-4312c34161aa)
i.e. provide citation via tying repo to Zenodo DOI, and stating the license terms.

**Comment by MattReimer** [comment]
Work done. Changes should appear once we get things publishing
