### ISSUE TITLE
Need way to update Gatsby site favicons with our new icons

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-gatsby-theme#2]
Here substitute the Gatsby logo with our new RC logo.
![image](https://github.com/Riverscapes/riverscapes-gatsby/assets/9723905/decfa089-1c40-475a-9275-b7fcd760c27d)

For other sites (e.g. Viewer site, we need to use the new icons).

Also, author the documentation for how to do this in new site documentation under developers.riverscapes.net

**Comment by MattReimer** [comment]
This is done and can now be specified with a fallback
