### ISSUE TITLE
Provide directions for how image standards

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-gatsby-theme#3]
Please work with @MattReimer to get some directions on where we should store images (I don't like them just in root of folder they are referenced from). I prefer that we put them in `{{ site.baseurl }}/src/images/` and use custom or thematic foldernames therein.

**Comment by MattReimer** [comment]
There is a demo page in the dev site that outlines all the different ways we can do images. 

I expect that @philipbaileynar will also add some stuff to the developer site once that's up

**Comment by MattReimer** [comment]
this is solved. See the demo page for details.
