### ISSUE TITLE
Add Help Widget to Footer and Update Contact Info

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-gatsby-theme#6]
- [ ] Update Contact Info to `support@riverscapes.freshdesk.com`
- [ ] Change `Contact` to `Support and Contact`
- [ ] Add Help Widget

![image](https://github.com/Riverscapes/riverscapes-gatsby/assets/9723905/68056dd2-7d1c-4a6d-9a45-bb1c1f0cf2c4)

@MattReimer  and @philipbaileynar this is a widget as a Freshworks RC Help Button (we can customize these and have as many as we want):
![image](https://github.com/Riverscapes/riverscapes-gatsby/assets/9723905/c7d99b60-ab95-4567-a9ea-1dcc1ba369cd)

On hover over it funnels towards knowledge base:
![image](https://github.com/Riverscapes/riverscapes-gatsby/assets/9723905/6f4e5ea6-2cfb-44c9-a681-5598a434cd86)

Or they can contact us if they need help:

![image](https://github.com/Riverscapes/riverscapes-gatsby/assets/9723905/7241b0d3-8269-46cd-ac3d-2f0841ea49a3)

Embed Code:
```
<script>
	window.fwSettings={
	'widget_id':153000000178
	};
	!function(){if("function"!=typeof window.FreshworksWidget){var n=function(){n.q.push(arguments)};n.q=[],window.FreshworksWidget=n}}() 
</script>
<script type='text/javascript' src='https://widget.freshworks.com/widgets/153000000178.js' async defer></script>
```

> Check out the [widget API documentation ](https://developers.freshdesk.com/widget-api)to explore advanced configurations like prefilling and hiding ticket fields, translating content, etc.

FYI @philipbaileynar , @dominique-shore and @jtgilbert. Let me know if you want any changes to widget.

**Comment by MattReimer** [comment]
The widget has been added but the position is non-negotiably the bottom right corner of the screen.
