### ISSUE TITLE
Provide better way for within site links.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-gatsby-theme#7]
As we discussed, the use of relative paths is going to be a non-starter for referencing pages for hyperlinks and for images. Please work with @MattReimer to figure out a solution more akin to what we have for the jekll sites where we use `{{ site.baseurl  }}` and we can avoid the `...\..\..\ relative path shitshow` that is way to error prone. Thanks.

**Comment by MattReimer** [comment]
You can use absolute OR relative links.
